### PR TITLE
The bot.py code is still messy, I'll try to resolve this later on

### PR DESCRIPTION
**Pull request by h4rldev**
Anyway, I did add some type of logging, kind of showing that it works by showing current lyric and song, I was gonna implement a check so that there isn't like 2 different music notes, or add some user customization.

### CODE REVIEW

**Comment by h4rldev** [comment]
I'll also add venv activation, dw

**Comment by h4rldev** [comment]
I've mostly focused on windows compat

**Comment by h4rldev** [comment]
You should also merge some enderflop commits

**Comment by h4rldev** [comment]
Since I am currently ratelimited lmao

**Comment by h4rldev** [comment]
I found an issue with my "logger" It doesn't update if the song is lyricless sometimes.

**Comment by r1sk01** [comment]
I might make a new branch for Windows support, this version is mainly for Linux support, gimme a bit of time to make a new branch and commit this to that

**Comment by h4rldev** [comment]
My branch It's compatible with both

**Review by r1sk01 — APPROVED** [review]

**Pull request merged**
